name = "yes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e507bdc147260f607f64f0e97b62fb670bbf2c9e45fdb2a3466c30a893c8fef"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
