name = "yes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d2f75697fa3ce11602a45f3e7a9f0e4b2a1bcace0b5d16cca4743d46479a0b6"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
