name = "yes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd8437299ef5253d271b599e3e9b4cbaea0da59ce02a8feae46b13ea577ae036"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
