name = "Cobblemon"
author = "not me lmao"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9712332687656a7266eae4a1821b9b9d8f12a950317ce466e61248e640ee11e"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
