name = "matcha-flavoured thingy"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30316dae72ba035da6c101b72188471e871145370319de110d68aeb7e89861e2"

[versions]
fabric = "0.19.5"
minecraft = "26.3"

[options]
datapack-folder = "config/paxi/datapacks"
